# Generated by Django 3.1.6 on 2021-02-27 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2021, 2, 27, 13, 13, 37, 815592))),
                ('published_at', models.DateTimeField(verbose_name=datetime.datetime(2021, 2, 27, 13, 13, 37, 815612))),
                ('status', models.CharField(max_length=7)),
            ],
        ),
    ]
