# Generated by Django 3.1.6 on 2021-02-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='published_at',
            field=models.DateField(),
        ),
    ]
