# Generated by Django 3.1.6 on 2021-02-27 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 2, 27, 13, 19, 13, 550446)),
        ),
        migrations.AlterField(
            model_name='review',
            name='published_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 2, 27, 13, 19, 13, 550465)),
        ),
    ]
