# Generated by Django 3.1.6 on 2021-02-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20210222_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='created_at',
            field=models.DateTimeField(unique_for_date=False),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='published_at',
            field=models.DateTimeField(unique_for_date=False),
        ),
    ]
