# Generated by Django 3.1.6 on 2021-02-27 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20210227_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 2, 27, 13, 26, 41, 822977)),
        ),
        migrations.AlterField(
            model_name='review',
            name='published_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 2, 27, 13, 26, 41, 822995)),
        ),
    ]
