# Generated by Django 3.1.6 on 2021-02-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20210227_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='published_at',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
